"""add platform_copy and review

Revision ID: 1787d080898a
Revises: d43fe63d0f74
Create Date: 2026-08-18 18:54:10.808073

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1787d080898a'
down_revision: str | Sequence[str] | None = 'd43fe63d0f74'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_copy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['summary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_copy_platform'), 'platform_copy', ['platform'], unique=False)
    op.create_index(op.f('ix_platform_copy_status'), 'platform_copy', ['status'], unique=False)
    op.create_index(op.f('ix_platform_copy_summary_id'), 'platform_copy', ['summary_id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copy_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['copy_id'], ['platform_copy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_copy_id'), 'review', ['copy_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_copy_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_platform_copy_summary_id'), table_name='platform_copy')
    op.drop_index(op.f('ix_platform_copy_status'), table_name='platform_copy')
    op.drop_index(op.f('ix_platform_copy_platform'), table_name='platform_copy')
    op.drop_table('platform_copy')
    # ### end Alembic commands ###
