"""add summary table

Revision ID: d43fe63d0f74
Revises: 60c00289d35c
Create Date: 2026-08-18 18:28:41.146441

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd43fe63d0f74'
down_revision: str | Sequence[str] | None = '60c00289d35c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('key_points', sa.JSON(), nullable=False),
    sa.Column('short_title', sa.String(length=200), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_article_id'), 'summary', ['article_id'], unique=True)
    op.create_index(op.f('ix_summary_status'), 'summary', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summary_status'), table_name='summary')
    op.drop_index(op.f('ix_summary_article_id'), table_name='summary')
    op.drop_table('summary')
    # ### end Alembic commands ###
